### ISSUE TITLE
Error: Error: Unknown protocol

### ISSUE THREAD

**Issue by DavidBeale** [benfoxall/puckmote#4]
Hi,

Great project!
 
Getting this error for LG -> TV and others using the NEC1 protocol.

![Screenshot 2021-09-01 at 13 50 36](https://user-images.githubusercontent.com/3041566/131674227-d433081a-c3a2-4b74-bcab-2154c138a236.png)

**Comment by benfoxall** [comment]
Hello! (Thanks!)

Ah, this sounds like it might be related to an issue that someone raised on the Espruino Forum, where the WebAssembly module [is missing some protocols](http://forum.espruino.com/conversations/363344/#:~:text=%20there%20are%20some%20protocols%20where%20definitions%20are%20not%20embed%20into%20the%20c%20file).

I'll have a bit more of a dig into it.  At the very least I should show a better error message in the UI 💥 .

Thanks for letting me know.

**Comment by DavidBeale** [comment]
Ar yes, that looks like it could be it

**Comment by DavidBeale** [comment]
Actually it looks like the protocol is in WASM, but the keys are different - IRDB has `NEC1` but MakeHex uses `NECx1`; also `NEC2` -> `NECx2`.

So maybe a quick fix is to add this mapping to the JS code?

**Comment by danielthepope** [comment]
There's also a lowercase `nec1` in EncodeIR.cpp (see [here](https://github.com/probonopd/MakeHex/blob/master/EncodeIR.cpp#L445)). I tried to change the `protocol` to lowercase before calling `Module.encode` in Ben's EncoreIR.js. That stopped the "Unknown protocol" error for me, but still didn't work with my TV; I'm starting to worry that the IR doesn't work on my Puck...

Calling toLowerCase() won't work widely though, because other protocols in that object have mixed case.

**Comment by deinhofer** [comment]
I also get the error message for several manufacturers, e.g. NEC, Panasonic, ...

Do you see a change to fix the error or could point me to a location how to do it?

We would like to integrate IrDB codes into our Open Source AAC web application [Asterics Grid](https://grid.asterics.eu/) in order to provide accessible control of IR devices with puck.js from within a grid. This could be very helpful for people with disabilities.

**Comment by deinhofer** [comment]
> I also get the error message for several manufacturers, e.g. NEC, Panasonic, ...
> 
> Do you see a change to fix the error or could point me to a location how to do it?
> 
> We would like to integrate IrDB codes into our Open Source AAC web application [Asterics Grid](https://grid.asterics.eu/) in order to provide accessible control of IR devices with puck.js from within a grid. This could be very helpful for people with disabilities.

Dear Ben, do think there would be a chance to fix this error? 
It seems that several devices don't work. I have had it for a Panasonic TV and an NEC beamer.

**Comment by JMwert00** [comment]
The problem with the unknown protocols seems to be different cases in the protocol names from `irdb` and the encoding library. See this test file for a fix: https://github.com/JMwert00/PuckTest/blob/main/encodeIRTest.html

**Comment by sabicalija** [comment]
I've created a fix for this issue (PR #5) accordingly.

**Comment by benfoxall** [comment]
@sabicalija thank you so much for the fix, I've merged your PR.

I just fixed an issue with the deploy, so now the site should be updated too 6f8f99cac3711207e3cd4541ec03667e4c88f78e 

@JMwert00 @deinhofer @danielthepope @DavidBeale I'm sorry for not getting on this sooner, thank you for raising and finding the issue. Much appreciated.

**Comment by sabicalija** [comment]
Please reopen the issue. There are cases where the fix doesn't work. I'll push a PR.
